name: 🚧 Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build
      - run: npm test:cov

      - uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: |
            coverage/
            test_reports/
